/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package online.gladikov.spi.app;

import org.junit.jupiter.api.Test;


import static org.junit.jupiter.api.Assertions.assertTrue;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertTrue(true);
    }
}
